import { readFile, stat, writeFile } from 'node:fs/promises';
import { extname } from 'node:path';
import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  ImageRun,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType
} from 'docx';
import sharp from 'sharp';
import type { ExportOptions, ExportResult } from '@shared/models/Ipc';
import type { Project } from '@shared/models/Project';
import type { RecordedStep } from '@shared/models/Step';
import { ImageOps } from '../capture/ImageOps';

const ACCENT = '0EA5E9';
const INK = '172033';
const MUTED = '64748B';
const BORDER = 'DBE3EF';
const SOFT = 'F8FAFC';
const imageOps = new ImageOps();

export async function exportDocx(project: Project, options: ExportOptions): Promise<ExportResult> {
  const steps = project.steps.filter((candidate) => options.includeDeletedSteps || !candidate.isDeleted);
  const children: Array<Paragraph | Table> = [
    new Paragraph({
      text: project.metadata.jiraKey || 'QA Report',
      heading: HeadingLevel.HEADING_3,
      spacing: { after: 120 }
    }),
    new Paragraph({
      children: [new TextRun({ text: project.metadata.title || 'QA Session Report', bold: true, size: 44, color: INK })],
      spacing: { after: 220 }
    })
  ];

  if (options.includeMetadata) children.push(metadataTable(project, steps.length));

  if (project.metadata.expected || project.metadata.actual) {
    children.push(sectionTitle('Expected / Actual'));
    children.push(resultsTable(project));
  }

  children.push(sectionTitle('Reproduction Steps'));

  for (const step of steps) {
    children.push(await stepTable(step, options));
  }

  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 240 },
    children: [new TextRun({ text: `Generated by StepForge on ${new Date().toLocaleString()}`, size: 18, color: MUTED })]
  }));

  const document = new Document({
    styles: {
      default: {
        document: { run: { font: 'Segoe UI', size: 22, color: INK }, paragraph: { spacing: { after: 120 } } }
      }
    },
    sections: [{
      properties: { page: { margin: { top: 720, right: 720, bottom: 720, left: 720 } } },
      children
    }]
  });
  const buffer = await Packer.toBuffer(document);
  await writeFile(options.outputPath, buffer);
  const outputStat = await stat(options.outputPath);
  return { outputPath: options.outputPath, sizeBytes: outputStat.size };
}

function metadataTable(project: Project, stepCount: number): Table {
  const items: Array<[string, string]> = [
    ['VAST / Jira', project.metadata.jiraKey || '-'],
    ['Tester', project.metadata.tester || '-'],
    ['Version', project.metadata.build || '-'],
    ['Environment', project.metadata.env || '-'],
    ['Priority', project.metadata.priority || '-'],
    ['Captured Steps', String(stepCount)]
  ];
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: tableBorders(BORDER),
    rows: [
      new TableRow({ children: items.slice(0, 3).map(metaCell) }),
      new TableRow({ children: items.slice(3).map(metaCell) })
    ]
  });
}

function metaCell([label, value]: [string, string]): TableCell {
  return new TableCell({
    width: { size: 33, type: WidthType.PERCENTAGE },
    shading: { type: ShadingType.CLEAR, fill: SOFT },
    margins: { top: 140, bottom: 140, left: 160, right: 160 },
    children: [
      new Paragraph({ children: [new TextRun({ text: label.toUpperCase(), bold: true, size: 16, color: MUTED })] }),
      new Paragraph({ children: [new TextRun({ text: value, bold: true, size: 22, color: INK })] })
    ]
  });
}

function resultsTable(project: Project): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: tableBorders(BORDER),
    rows: [new TableRow({ children: [resultCell('Expected', project.metadata.expected || '-'), resultCell('Actual', project.metadata.actual || '-')] })]
  });
}

function resultCell(label: string, value: string): TableCell {
  return new TableCell({
    width: { size: 50, type: WidthType.PERCENTAGE },
    shading: { type: ShadingType.CLEAR, fill: label === 'Expected' ? 'F0FDF4' : 'FEF2F2' },
    margins: { top: 160, bottom: 160, left: 180, right: 180 },
    children: [
      new Paragraph({ children: [new TextRun({ text: label, bold: true, size: 20, color: label === 'Expected' ? '166534' : '991B1B' })] }),
      new Paragraph({ children: [new TextRun({ text: value, size: 21, color: INK })] })
    ]
  });
}

async function stepTable(step: RecordedStep, options: ExportOptions): Promise<Table> {
  const body: Paragraph[] = [];
  const tags = [step.window?.title || '-', options.includeTimestamps ? new Date(step.timestamp).toLocaleString() : ''].filter(Boolean).join('   |   ');
  body.push(new Paragraph({ children: [new TextRun({ text: step.description, bold: true, size: 25, color: INK })] }));
  if (tags) body.push(new Paragraph({ children: [new TextRun({ text: tags, size: 18, color: MUTED })] }));
  if (step.warnings?.length) {
    step.warnings.forEach((warning) => body.push(new Paragraph({ children: [new TextRun({ text: `Warning: ${warning.message}`, bold: true, color: '92400E' })] })));
  }
  if (options.includeNotes && step.userNote) {
    body.push(new Paragraph({ children: [new TextRun({ text: `Note: ${step.userNote}`, italics: true, color: '744210' })] }));
  }
  if (options.includeScreenshots && step.screenshotPath) {
    body.push(await screenshotParagraph(step));
  }

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: tableBorders(BORDER),
    rows: [new TableRow({
      cantSplit: true,
      children: [
        new TableCell({
          width: { size: 10, type: WidthType.PERCENTAGE },
          shading: { type: ShadingType.CLEAR, fill: ACCENT },
          margins: { top: 180, bottom: 180, left: 120, right: 120 },
          children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: String(step.stepNumber), bold: true, size: 28, color: 'FFFFFF' })] })]
        }),
        new TableCell({
          width: { size: 90, type: WidthType.PERCENTAGE },
          margins: { top: 180, bottom: 180, left: 200, right: 200 },
          children: body
        })
      ]
    })]
  });
}

async function screenshotParagraph(step: RecordedStep): Promise<Paragraph> {
  try {
    const imageBytes = await imageOps.renderExportImage(await readFile(step.screenshotPath), step.annotations ?? []);
    const size = await imageSize(step.screenshotPath);
    return new Paragraph({
      spacing: { before: 120 },
      children: [new ImageRun({
        type: imageType(step.screenshotPath),
        data: imageBytes,
        transformation: size,
        altText: { title: step.description, description: `Screenshot for step ${step.stepNumber}`, name: `step-${step.stepNumber}` }
      })]
    });
  } catch {
    return new Paragraph({ children: [new TextRun({ text: `Screenshot unavailable: ${step.screenshotPath}`, color: '991B1B' })] });
  }
}

function sectionTitle(text: string): Paragraph {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 140 } });
}

function tableBorders(color: string) {
  return {
    top: { style: BorderStyle.SINGLE, size: 1, color },
    bottom: { style: BorderStyle.SINGLE, size: 1, color },
    left: { style: BorderStyle.SINGLE, size: 1, color },
    right: { style: BorderStyle.SINGLE, size: 1, color },
    insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color },
    insideVertical: { style: BorderStyle.SINGLE, size: 1, color }
  };
}

async function imageSize(path: string): Promise<{ width: number; height: number }> {
  const metadata = await sharp(path).metadata();
  const nativeWidth = metadata.width || 1200;
  const nativeHeight = metadata.height || 750;
  const width = Math.min(620, nativeWidth);
  return { width, height: Math.max(1, Math.round(width * (nativeHeight / nativeWidth))) };
}

function imageType(path: string): 'jpg' | 'png' | 'gif' | 'bmp' {
  const extension = extname(path).toLowerCase();
  if (extension === '.jpg' || extension === '.jpeg') return 'jpg';
  if (extension === '.gif') return 'gif';
  if (extension === '.bmp') return 'bmp';
  return 'png';
}