import { readFile } from 'node:fs/promises';
import type { ExportOptions } from '@shared/models/Ipc';
import type { Project } from '@shared/models/Project';
import type { RecordedStep } from '@shared/models/Step';

export async function renderReportHtml(project: Project, options: ExportOptions): Promise<string> {
  const compact = options.format === 'HtmlCompact';
  const steps = project.steps.filter((step) => options.includeDeletedSteps || !step.isDeleted);
  const stepCards = await Promise.all(steps.map((step) => renderStep(step, options, compact)));
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(project.metadata.title)}</title>${styles(compact)}</head><body><main class="report"><section class="cover"><div class="eyebrow">${escapeHtml(project.metadata.jiraKey || 'QA report')}</div><h1>${escapeHtml(project.metadata.title || 'QA Session Report')}</h1>${metadata(project, options)}${summary(steps.length)}</section><section class="content">${results(project)}<h2>Reproduction Steps</h2>${stepCards.join('')}<footer>Generated by StepForge on ${escapeHtml(new Date().toLocaleString())}</footer></section></main></body></html>`;
}

async function renderStep(step: RecordedStep, options: ExportOptions, compact: boolean): Promise<string> {
  const image = options.includeScreenshots && step.screenshotPath ? await imageTag(step, options) : '';
  const note = options.includeNotes && step.userNote ? `<div class="note"><strong>Note:</strong> ${escapeHtml(step.userNote)}</div>` : '';
  const warnings = step.warnings?.length
    ? `<div class="warnings">${step.warnings.map((warning) => `<div>${escapeHtml(warning.message)}</div>`).join('')}</div>`
    : '';
  const timestamp = options.includeTimestamps ? `<span>${escapeHtml(new Date(step.timestamp).toLocaleTimeString())}</span>` : '';
  return `<article class="step ${compact ? 'compact' : ''}"><div class="badge">${step.stepNumber}</div><div><h3>${escapeHtml(step.description)}</h3><div class="tags"><span>${escapeHtml(step.window?.title ?? '-')}</span>${timestamp}</div>${warnings}${image}${note}</div></article>`;
}

async function imageTag(step: RecordedStep, options: ExportOptions): Promise<string> {
  if (options.embedImagesAsBase64) {
    const bytes = await readFile(step.screenshotPath);
    return `<img src="data:image/png;base64,${bytes.toString('base64')}" alt="${escapeHtml(step.description)}">`;
  }
  return `<img src="${escapeAttribute(step.screenshotPath)}" alt="${escapeHtml(step.description)}">`;
}

function metadata(project: Project, options: ExportOptions): string {
  if (!options.includeMetadata) return '';
  const items = [
    ['VAST / Jira', project.metadata.jiraKey || '-'],
    ['Tester', project.metadata.tester],
    ['Version', project.metadata.build],
    ['Environment', project.metadata.env],
    ['Priority', project.metadata.priority]
  ];
  return `<div class="meta">${items.map(([label, value]) => `<div><b>${escapeHtml(label)}</b><span>${escapeHtml(value || '-')}</span></div>`).join('')}</div>`;
}

function results(project: Project): string {
  if (!project.metadata.expected && !project.metadata.actual) return '';
  return `<div class="results"><div><b>Expected</b><p>${escapeHtml(project.metadata.expected)}</p></div><div><b>Actual</b><p>${escapeHtml(project.metadata.actual)}</p></div></div>`;
}

function styles(compact: boolean): string {
  return `<style>body{margin:0;background:#edf2f7;color:#1a202c;font-family:Segoe UI,Arial,sans-serif}.report{max-width:${compact ? 780 : 1060}px;margin:32px auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.18)}.cover{padding:${compact ? 28 : 42}px;background:#ffffff;color:#172033;border-bottom:1px solid #dbe3ef}.eyebrow{text-transform:uppercase;letter-spacing:.16em;font-size:11px;font-weight:800;color:#0ea5e9}h1{margin:8px 0 0;font-size:${compact ? 24 : 34}px;line-height:1.15;color:#0f172a}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:22px}.meta div{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:10px}.meta b{display:block;font-size:9px;text-transform:uppercase;color:#64748b}.meta span{display:block;margin-top:3px;font-weight:700;color:#172033}.summary{margin-top:16px;display:inline-flex;gap:7px;align-items:baseline;background:#ecfeff;border:1px solid #bae6fd;border-radius:999px;padding:6px 12px;color:#0369a1}.summary b{font-size:16px}.summary span{font-size:11px;font-weight:700}.content{padding:${compact ? 24 : 42}px}.results{display:grid;grid-template-columns:1fr 1fr;gap:14px}.results div{border-left:4px solid #16a34a;background:#f0fdf4;padding:10px 14px;border-radius:6px}.results div+div{border-left-color:#dc2626;background:#fef2f2}.step{display:grid;grid-template-columns:44px 1fr;gap:14px;border:1px solid #e2e8f0;border-radius:12px;padding:${compact ? 14 : 20}px;margin:14px 0;box-shadow:0 2px 8px rgba(0,0,0,.04);break-inside:avoid}.badge{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;background:#0ea5e9;color:white;font-weight:800}h2{color:#0f172a}h3{margin:0 0 8px;font-size:15px;color:#172033}.tags{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.tags span{background:#edf2f7;color:#4a5568;border-radius:4px;padding:2px 7px;font-size:11px}.warnings{display:grid;gap:5px;margin:8px 0}.warnings div{background:#fffbeb;border:1px solid #fde68a;color:#92400e;border-radius:6px;padding:6px 8px;font-size:11px}img{width:100%;max-height:${compact ? 300 : 520}px;object-fit:contain;background:#0f172a;border-radius:8px;border:1px solid #e2e8f0}.note{margin-top:10px;padding:8px 12px;border-left:3px solid #f59e0b;background:#fffbeb;border-radius:4px;color:#744210}footer{text-align:center;color:#64748b;border-top:1px solid #edf2f7;margin-top:24px;padding-top:14px;font-size:11px}</style>`;
}
function summary(stepCount: number): string {
  return `<div class="summary"><b>${stepCount}</b><span>captured step${stepCount === 1 ? '' : 's'}</span></div>`;
}

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[char] ?? char);
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replace(/'/g, '&#39;');
}