import type { Project, SessionMetadata } from '@shared/models/Project';
import type { RecordedStep } from '@shared/models/Step';
import { formatClock } from '@shared/util/time';

interface Props {
  project: Project;
  mode: 'full' | 'compact';
}

export function ReportPreview({ project, mode }: Props) {
  const compact = mode === 'compact';
  const { metadata, steps } = project;
  const visibleSteps = steps.filter((step) => !step.isDeleted);
  const bugCount = visibleSteps.filter((step) => step.flags.includes('Bug')).length;
  const importantCount = visibleSteps.filter((step) => step.flags.includes('Important')).length;
  return (
    <div
      style={{
        width: '100%',
        maxWidth: compact ? 780 : 1060,
        flexShrink: 0,
        background: '#f8fafc',
        borderRadius: 8,
        overflow: 'hidden',
        boxShadow: '0 18px 50px rgba(0,0,0,0.34), 0 0 0 1px rgba(148,163,184,0.24)',
        color: '#172033',
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'
      }}
    >
      <Cover meta={metadata} compact={compact} stepCount={visibleSteps.length} bugCount={bugCount} />

      <div
        style={{
          padding: compact ? '22px 28px 30px' : '30px 42px 42px',
          display: 'flex',
          flexDirection: 'column',
          gap: compact ? 14 : 18
        }}
      >
        <SummaryStrip
          meta={metadata}
          stepCount={visibleSteps.length}
          bugCount={bugCount}
          importantCount={importantCount}
          compact={compact}
        />

        {(metadata.expected || metadata.actual) && (
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: compact ? '1fr' : '1fr 1fr',
              gap: 12
            }}
          >
            <ResultCard kind="expected" text={metadata.expected} />
            <ResultCard kind="actual" text={metadata.actual} />
          </div>
        )}

        <SectionTitle title="Reproduction Steps" detail={`${visibleSteps.length} captured`} />

        <div style={{ display: 'flex', flexDirection: 'column', gap: compact ? 12 : 16 }}>
          {visibleSteps.map((step) => (
            <StepCard key={step.id} step={step} compact={compact} />
          ))}
        </div>

        <div
          style={{
            marginTop: 6,
            padding: '14px 0 0',
            borderTop: '1px solid #dbe3ef',
            fontSize: 11,
            color: '#64748b',
            textAlign: 'center'
          }}
        >
          Generated by Kayle&apos;s Steps Recorder on {formatClock(metadata.startedAt)}
        </div>
      </div>
    </div>
  );
}

function Cover({
  meta,
  compact,
  stepCount,
  bugCount
}: {
  meta: SessionMetadata;
  compact: boolean;
  stepCount: number;
  bugCount: number;
}) {
  const vastId = formatVastId(meta.jiraKey || meta.title);
  return (
    <div
      style={{
        padding: compact ? '26px 28px' : '34px 42px',
        background: '#ffffff',
        borderBottom: '1px solid #dbe3ef',
        color: '#172033'
      }}
    >
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 18 }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={eyebrowStyle}>{vastId}</div>
          <div
            style={{
              fontSize: compact ? 22 : 30,
              fontWeight: 800,
              marginTop: 7,
              lineHeight: 1.15,
              color: '#0f172a'
            }}
          >
            {meta.title || 'QA Session Report'}
          </div>
        </div>
        <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
          <Metric value={stepCount} label="Steps" />
          <Metric value={bugCount} label="Bugs" tone={bugCount > 0 ? 'danger' : 'neutral'} />
        </div>
      </div>
    </div>
  );
}

function formatVastId(title: string): string {
  const clean = title.trim();
  if (!clean) return 'VAST-';
  const vastMatch = clean.match(/^VAST-?(\d+)$/i);
  if (vastMatch?.[1]) return `VAST-${vastMatch[1]}`;
  return clean.toUpperCase();
}

function SummaryStrip({
  meta,
  stepCount,
  bugCount,
  importantCount,
  compact
}: {
  meta: SessionMetadata;
  stepCount: number;
  bugCount: number;
  importantCount: number;
  compact: boolean;
}) {
  const items: [string, string][] = [
    ['Build', meta.build || '-'],
    ['Priority', meta.priority || '-'],
    ['Tester', meta.tester || '-'],
    ['Captured', `${stepCount} steps`],
    ['Flagged', `${bugCount} bug / ${importantCount} important`]
  ];
  return (
    <div
      style={{
        display: 'grid',
        gridTemplateColumns: compact ? '1fr 1fr' : 'repeat(5, 1fr)',
        gap: 1,
        overflow: 'hidden',
        borderRadius: 8,
        border: '1px solid #dbe3ef',
        background: '#dbe3ef'
      }}
    >
      {items.map(([label, value]) => (
        <div key={label} style={{ background: '#ffffff', padding: '10px 12px', minWidth: 0 }}>
          <div style={smallLabelStyle}>{label}</div>
          <div
            style={{
              fontSize: 12,
              fontWeight: 700,
              color: '#1e293b',
              marginTop: 3,
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap'
            }}
          >
            {value}
          </div>
        </div>
      ))}
    </div>
  );
}

function SectionTitle({ title, detail }: { title: string; detail: string }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 2 }}>
      <h2 style={{ fontSize: 15, fontWeight: 800, margin: 0, color: '#172033' }}>{title}</h2>
      <div style={{ flex: 1, height: 1, background: '#dbe3ef' }} />
      <span style={{ fontSize: 11, color: '#64748b', fontWeight: 700 }}>{detail}</span>
    </div>
  );
}

function Metric({ value, label, tone = 'neutral' }: { value: number; label: string; tone?: 'neutral' | 'danger' }) {
  return (
    <div
      style={{
        minWidth: 66,
        borderRadius: 7,
        border: `1px solid ${tone === 'danger' ? '#fecaca' : '#dbe3ef'}`,
        background: tone === 'danger' ? '#fff1f2' : '#f8fafc',
        padding: '8px 10px',
        textAlign: 'center'
      }}
    >
      <div style={{ fontSize: 18, fontWeight: 800, color: tone === 'danger' ? '#b91c1c' : '#172033' }}>{value}</div>
      <div style={{ ...smallLabelStyle, marginTop: 1 }}>{label}</div>
    </div>
  );
}

function ResultCard({ kind, text }: { kind: 'expected' | 'actual'; text: string }) {
  const cfg =
    kind === 'expected'
      ? { c: '#047857', bg: '#ecfdf5', border: '#a7f3d0', l: 'Expected' }
      : { c: '#b91c1c', bg: '#fff1f2', border: '#fecaca', l: 'Actual' };
  return (
    <div
      style={{
        border: `1px solid ${cfg.border}`,
        borderLeft: `4px solid ${cfg.c}`,
        background: cfg.bg,
        padding: '12px 14px',
        borderRadius: 8
      }}
    >
      <div
        style={{
          fontSize: 10,
          fontWeight: 700,
          color: cfg.c,
          textTransform: 'uppercase',
          letterSpacing: '0.1em'
        }}
      >
        {cfg.l}
      </div>
      <div style={{ fontSize: 13, color: '#243449', marginTop: 5, lineHeight: 1.55 }}>
        {text || '-'}
      </div>
    </div>
  );
}

function StepCard({ step, compact }: { step: RecordedStep; compact: boolean }) {
  const flagged = step.flags.includes('Bug')
    ? 'bug'
    : step.flags.includes('Important')
      ? 'important'
      : null;
  const accent = flagged === 'bug' ? '#dc2626' : flagged === 'important' ? '#d97706' : '#0ea5e9';
  const flagBg = flagged === 'bug' ? '#fff1f2' : flagged === 'important' ? '#fffbeb' : '#eff6ff';
  const flagText = flagged === 'bug' ? '#991b1b' : flagged === 'important' ? '#92400e' : '#075985';
  return (
    <div
      style={{
        background: '#ffffff',
        border: '1px solid #dbe3ef',
        borderRadius: 8,
        padding: compact ? '14px 16px' : '18px 20px',
        borderLeft: `4px solid ${accent}`,
        boxShadow: '0 1px 2px rgba(15,23,42,0.04)',
        display: 'grid',
        gridTemplateColumns: '38px 1fr',
        gap: 12
      }}
    >
      <div
        style={{
          width: 30,
          height: 30,
          borderRadius: 6,
          background: flagBg,
          color: flagText,
          border: `1px solid ${flagged === 'bug' ? '#fecaca' : flagged === 'important' ? '#fde68a' : '#bae6fd'}`,
          fontWeight: 800,
          fontSize: 13,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center'
        }}
      >
        {step.stepNumber}
      </div>
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
          <div
            style={{
              fontSize: compact ? 13 : 14,
              fontWeight: 800,
              color: '#172033'
            }}
          >
            {step.description}
          </div>
          {flagged && (
            <span
              style={{
                fontSize: 9,
                fontWeight: 700,
                textTransform: 'uppercase',
                letterSpacing: '0.08em',
                padding: '2px 7px',
                borderRadius: 4,
                background: flagBg,
                color: flagText
              }}
            >
              {flagged}
            </span>
          )}
        </div>
        <div style={{ display: 'flex', gap: 6, marginBottom: 8 }}>
          <span style={tagStyle}>{step.window?.title ?? '—'}</span>
          <span
            style={{
              ...tagStyle,
              fontFamily: 'ui-monospace, monospace'
            }}
          >
            {formatClock(step.timestamp)}
          </span>
        </div>
        <div
          style={{
            borderRadius: 8,
            overflow: 'hidden',
            border: '1px solid #cbd5e1',
            boxShadow: '0 1px 3px rgba(15,23,42,0.12)',
            background: '#111827',
            aspectRatio: compact ? '16 / 9' : '16 / 10',
            maxHeight: compact ? 250 : 380,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'rgba(226,232,240,0.5)',
            fontFamily: 'ui-monospace, monospace',
            fontSize: 11
          }}
        >
          {step.screenshotPath ? (
            <img
              src={'file://' + step.screenshotPath}
              alt={step.description}
              style={{ width: '100%', height: '100%', objectFit: 'contain' }}
            />
          ) : (
            <span>SCREENSHOT</span>
          )}
        </div>
        {step.userNote && (
          <div
            style={{
              marginTop: 10,
              padding: '9px 11px',
              border: '1px solid #fde68a',
              borderLeft: '3px solid #d97706',
              background: '#fffbeb',
              borderRadius: 4,
              fontSize: 12,
              color: '#744210'
            }}
          >
            <strong>Note:</strong> {step.userNote}
          </div>
        )}
      </div>
    </div>
  );
}

const tagStyle: React.CSSProperties = {
  display: 'inline-block',
  padding: '2px 7px',
  background: '#eef2f7',
  color: '#475569',
  borderRadius: 4,
  fontSize: 11,
  fontWeight: 500
};

const eyebrowStyle: React.CSSProperties = {
  fontSize: 10,
  fontWeight: 800,
  letterSpacing: '0.14em',
  textTransform: 'uppercase',
  color: '#0284c7'
};

const smallLabelStyle: React.CSSProperties = {
  fontSize: 9,
  fontWeight: 800,
  letterSpacing: '0.12em',
  textTransform: 'uppercase',
  color: '#64748b'
};
